### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by escherstair** [ARM-software/CMSIS-FreeRTOS#56]
In README.md I see

> The branch master of this GitHub repository contains the CMSIS-RTOS adoption of [FreeRTOS Version 10.4.6](https://github.com/FreeRTOS/FreeRTOS/releases/download/202111.00/FreeRTOSv202111.00.zip) as it is released as Software Pack on http://www.keil.com/pack.

I think that the information about FreeRTOS version is a little bit confusing, since the text shows Version 10.4.6 but the link points to Version 202111.00.
And in tbis way it's not clear for the end user if CMSIS-FreeRTOS is up-to-date with upstream FreeRTOS or not.

After my investigation I think that this happens because CMSIS-FreeRTOS is not an adoption of FreeRTOS [here](https://github.com/FreeRTOS/FreeRTOS), but of FreeRTOS-Kernel [here](https://github.com/FreeRTOS/FreeRTOS-Kernel).
And keeping this in mind, everything is much clearer, since FreeRTOS-Kernel is at version 10.4.6.

My suggestion is to change the README.md in this way
> The branch master of this GitHub repository contains the CMSIS-RTOS adoption of [FreeRTOS-Kernel Version 10.4.6](https://github.com/FreeRTOS/FreeRTOS-Kernel/archive/refs/tags/V10.4.6.zip) as it is released as Software Pack on http://www.keil.com/pack.

What do you think?

**Comment by VladimirUmek** [comment]
Hi,
sorry for a late reply! Your comment has been taken into account but there were no changes so far. Currently CMSIS-FreeRTOS pack somehow adopts "Classic" FreeRTOS structure (at the time not entirely true due to the historic reasons) and just updating the kernel from a different repository would introduce another mess.
We'll try to address the issue and make pack structure consistent with the most appropriate repository.

**Comment by VladimirUmek** [comment]
This has been now addressed. CMSIS-FreeRTOS is no longer updated from 'Classic' FreeRTOS - primary source is now the FreeRTOS-Kernel repository.
